### ISSUE TITLE
Don't rebuild protobuf, use the OS one

### ISSUE THREAD

**Issue by KOLANICH** [neoml-lib/neoml#12]
https://cmake.org/cmake/help/latest/module/FindProtobuf.html

**Comment by TemplateVoid** [comment]
Yes, it’s more correct to use find_package. This will be fixed soon.

**Comment by lordnn** [comment]
You may have a reason to use self-build protobuf. But, please remove protobuf methods from the list of exported from libNeoOnnx.so.

**Comment by FedyuninV** [comment]
Ooups, we've forgottten to close this one. (PRs above fixed the issue)

**Comment by KOLANICH** [comment]
Thank you.
