### ISSUE TITLE
Not supported by NeoOnnx: operator Transpose

### ISSUE THREAD

**Issue by Vovkin81** [neoml-lib/neoml#359]
Hello.
I'm trying to load the onnx-model after the tf2onnx.convert converter, the program is interrupted with an error: 
"Not supported by NeoOnnx: operator Transpose". 

I use the ONNX opset version 9. Same error when trying to load any model from [https://github.com/onnx/models](url)

How do I solve this?

**Comment by FedyuninV** [comment]
Hello.

The support of this operator (and some others) will be added soon. I'll comment here when it's done.

**Comment by FedyuninV** [comment]
Hello again.

As a result we've decided to heavily refactor NeoOnnx.
Now refactoring is finished (#421) and NeoOnnx supports more operators (including `Transpose`).
