### ISSUE TITLE
protobuf errors on Astra Linux on master 

### ISSUE THREAD

**Issue by rmk177** [neoml-lib/neoml#42]
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/bin/ld: final link failed: Раздел, непредставимый для вывода
collect2: error: ld returned 1 exit status
NeoOnnx/src/CMakeFiles/NeoOnnx.dir/build.make:581: ошибка выполнения рецепта для цели «NeoOnnx/src/libNeoOnnx.so»
make[2]: *** [NeoOnnx/src/libNeoOnnx.so] Ошибка 1
CMakeFiles/Makefile2:266: ошибка выполнения рецепта для цели «NeoOnnx/src/CMakeFiles/NeoOnnx.dir/all»
make[1]: *** [NeoOnnx/src/CMakeFiles/NeoOnnx.dir/all] Ошибка 2
Makefile:160: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by FedyuninV** [comment]
День добрый.

Мы используем Position-Independent Code (PIC), и потому для работы с protobuf его надо собрать с тем же флагом.

Для этого при сборке protobuf во время конфигурации надо передать доп. параметры:
```c++
./configure "CFLAGS=-fPIC" "CXXFLAGS=-fPIC"
```

Подробнее можно прочесть [здесь](https://github.com/protocolbuffers/protobuf/issues/1919)

**Comment by TemplateVoid** [comment]
Or use set(CMAKE_POSITION_INDEPENDENT_CODE ON) in cmake...

**Comment by rmk177** [comment]
Собралось нормально.
Спасибо.
Есть только один момент. Для специальных ОС(Astra Linux Smolensk) все пакеты подписаны и пересобирать их нельзя. Так как вы говорили что будете разрабатывать под нейропроцессоры Модуль продумайте совместимость "из коробки" с такими ОС.
