### ISSUE TITLE
error LNK2019 when building the library NeoOnnx.dll

### ISSUE THREAD

**Issue by Vovkin81** [neoml-lib/neoml#470]
Hello.
I am building a library on windows 10, MSVC 2019 x64, protobuf 3.18.1 . I get two errors:

onnx.pb.obj : error LNK2019: ссылка на неразрешенный внешний символ "class google::protobuf::internal::ExplicitlyConstr
ucted<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::inter
nal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A) в функции "public: virtual class onnx::ValueInfoProto* __cdecl onnx::ValueInfoProto::New(void)const " (?New@ValueInfoProto@onnx@@UEBAPEAV12@XZ). [H:\libs\neoml2.0.22.0\Build\NeoOnnx\src\NeoOnnx.vcxproj]

onnx.pb.obj : error LNK2019: ссылка на неразрешенный внешний символ "struct std::atomic<bool> google::protobuf::interna
l::init_protobuf_defaults_state" (?init_protobuf_defaults_state@internal@protobuf@google@@3U?$atomic@_N@std@@A) в функции "public: virtual unsigned char * __cdecl onnx::TensorShapeProto_Dimension::_InternalSerialize(unsigned char *,class
google::protobuf::io::EpsCopyOutputStream *)const " (?_InternalSerialize@TensorShapeProto_Dimension@onnx@@UEBAPEAEPEAEPEAVEpsCopyOutputStream@io@protobuf@google@@@Z). [H:\libs\neoml2.0.22.0\Build\NeoOnnx\src\NeoOnnx.vcxproj]

H:\libs\neoml2.0.22.0\Build\NeoOnnx\src\Release\NeoOnnx.dll : fatal error LNK1120: неразрешенных внешних элементов: 2 [
H:\libs\neoml2.0.22.0\Build\NeoOnnx\src\NeoOnnx.vcxproj]

How fix it?
Thank you!

**Comment by FedyuninV** [comment]
This is protobuf-related problem https://github.com/protocolbuffers/protobuf/issues/2502 and it occurs when trying to link protobuf dynamically.

It can be fixed by adding `-DCMAKE_CXX_FLAGS='-DPROTOBUF_USE_DLLS'` to the NeoML's generating command.

(If you don't need ONNX import, then you can just add `-DNeoOnnx_BUILD=OFF` and get rid of protobuf dependency)

**Comment by FedyuninV** [comment]
Now it should work without explicit `-DCMAKE_CXX_FLAGS='-DPROTOBUF_USE_DLLS'`
