### ISSUE TITLE
Clamp proposal

### ISSUE THREAD

**Issue by lordnn** [neoml-lib/neoml#496]
Раз PR вы не принимаете, оформлю как issue.
Сделайте в `namespace NeoML` себе что-то такое и перестаньте писать многоэтажные сравнения:

```
#if __cplusplus >= 201703L
using std::clamp;
#else
template<typename T, typename Compare = std::less<T>> constexpr const T& clamp(const T &v, const T &lo, const T &hi, Compare comp = Compare()) {
    return comp(v, lo) ? lo : comp(hi, v) ? hi : v;
}
#endif
```

**Comment by FedyuninV** [comment]
Идея хорошая, но где именно нашлось столько многоэтажных сравнений?

Просто по некоторым причинам нам лучше минимизировать использование `std::` вне `NeoMathEngine`.

**Comment by lordnn** [comment]
https://github.com/neoml-lib/neoml/blob/5189ed0f26abff70c413ea40ccd6b7b9f9ee9435/NeoOnnx/src/AttributeGetters.h#L62-L68
https://github.com/neoml-lib/neoml/blob/5189ed0f26abff70c413ea40ccd6b7b9f9ee9435/NeoOnnx/src/AttributeGetters.h#L90-L96
https://github.com/neoml-lib/neoml/blob/5189ed0f26abff70c413ea40ccd6b7b9f9ee9435/NeoOnnx/src/TensorUtils.h#L41-L47
https://github.com/neoml-lib/neoml/blob/5189ed0f26abff70c413ea40ccd6b7b9f9ee9435/NeoOnnx/src/TensorUtils.h#L116-L122
Бонус:
https://github.com/neoml-lib/neoml/blob/5189ed0f26abff70c413ea40ccd6b7b9f9ee9435/NeoOnnx/src/TensorUtils.h#L102-L106
Это - std::min

Любопытно, бОльшая часть STL это headers-only шаблоны, т.е. runtime-зависимости они не добавляют или у вас есть платформы где есть C++ компилятор но нет стандартной библиотеки? Поделитесь печалью.

P.S. _Нет ~~бога кроме~~ С++ без STL и Страуструп - пророк его._

**Comment by lordnn** [comment]
Можете переизобрести "велосипед" `std::less` и получится обойтись без `std::`...

**Comment by FedyuninV** [comment]
Причиной, по некоторым причинам, предпочту не делиться)

Но в NeoOnnx думаю можно добавить `clamp` даже с `std::`
