### ISSUE TITLE
Functional API functor without connections restrictions

### ISSUE THREAD

**Issue by DmitrySolntsev** [neoml-lib/neoml#582]
It will be nice to have general functor in CLayerWrapper without restriction in inputs amount. It wil be useful for layers like Concat etc.

General functor sugestion:
```
// Connects inputs to the layer.
T* operator()( const CArray<CDnnLayerLink>& layers );
```

**Comment by favorart** [comment]
Fixed in
* https://github.com/neoml-lib/neoml/pull/1108
