### ISSUE TITLE
Wrap NeoOnnx into NeoML/Python

### ISSUE THREAD

**Issue by zimka** [neoml-lib/neoml#696]
In most cases .onnx models are produced from Python environment  - e.g. from `tensorflow + tf2onnx` or `torch + torch.onnx.export`). 
Currently to convert such exported onnx models into NeoML you can use either executable app (`NeoOnnx/Onnx2NeoML`) or C++ API (`NeoOnnx::LoadFromOnnx`).

It would be nice to wrap NeoOnnx API into python bindings. With such Python API it would be possible to run the whole conversion pipeline (third-party-framework export, neoml import, models comparison and checks) in one environment.

**Comment by FedyuninV** [comment]
Yep, we know. The work is [in progress](https://github.com/FedyuninV/neoml/tree/PyOnnxExperiments/NeoML/Python/neoml/Onnx) but I can't tell you when it will be moved to master...

**Comment by favorart** [comment]
Fixed in
* https://github.com/neoml-lib/neoml/pull/745
